[package]
name = "lists"
version = "0.1.0"
authors = ["paranoidandroid81 <mpk44@pitt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
